webapp/__init__.py
from flask import Flask, redirect, url_for

from .models import db, User, Role
from .controllers.main import main_blueprint
from .controllers.zako.views import zako_blueprint
from .controllers.forum import forum_blueprint
from .extensions import bcrypt
from .filters import datetimeformat


def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    bcrypt.init_app(app)

    app.register_blueprint(main_blueprint)
    app.register_blueprint(zako_blueprint)
    app.register_blueprint(forum_blueprint)

    app.jinja_env.filters['datetimeformat'] = datetimeformat

    return app


if __name__ == "__main__":
    app = create_app()

webapp/controllers/forum.py
# coding: utf-8
''' forum 论坛控制器视图
'''
import datetime
from collections import namedtuple
from sqlalchemy import func
from flask import render_template, Blueprint, redirect, url_for, flash, session, request, make_response, g, abort
from webapp.models import db, User, Post, Comment, PostCategory
from webapp.forms import PostForm, CommentForm, select_choice_names


forum_blueprint = Blueprint(
    'forum',
    __name__,
    template_folder='../templates/forum',
    url_prefix='/forum'
)

category_tuple = namedtuple('Category', ['code', 'name'])
sort_key_tuple = namedtuple('SortKey', ['code', 'name'])


categories = {k: v for (k, v) in [(x.code, x) for x in (category_tuple(
    x[0], x[1]) for x in zip([i.name for i in PostCategory], select_choice_names))]}
sort_keys = {
    'recent': sort_key_tuple('recent', '最新'),
    'hotest': sort_key_tuple('hotest', '最热')
}


@forum_blueprint.before_request
def check_user():
    if 'username' in session:
        g.current_user = User.query.filter_by(
            username=session["username"]
        ).one()
    else:
        g.current_user = None


@forum_blueprint.route('/<string:category>/<string:sort_key>')
def index(category, sort_key):
    page = request.args.get('p', 1, type=int)
    print(page)
    if category not in categories.keys():
        abort(404)
    if sort_key not in sort_keys.keys():
        abort(404)
    if sort_key == "recent":
        posts = db.session.query(Post, func.count(Comment.post_id).label(
            'total_comments')).join(Comment, isouter=True).filter(Post.category == category).group_by(Post.id).order_by(Post.publish_date.desc()).paginate(int(page), 10, False)
    else:
        posts = db.session.query(Post, func.count(Comment.post_id).label('total_comments')).join(Comment, isouter=True).filter(
            Post.category == category).group_by(Post.id).order_by('total_comments DESC').paginate(int(page), 10, False)
    return render_template('forum.html', category=categories[category], sort=sort_keys[sort_key], posts=posts)


@forum_blueprint.route('/t/<int:post_id>', methods=['GET', 'POST'])
def get_post(post_id):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    if g.current_user and form.validate_on_submit():
        comment = Comment(form.text.data)
        comment.post_id = post_id
        comment.user_id = g.current_user.id
        comment.date = datetime.datetime.now()
        db.session.add(comment)
        db.session.commit()
        form.text.data = ""

    return render_template('post.html', post=post, form=form)


@forum_blueprint.route('/add', methods=['GET', 'POST'])
def add_post():
    if not g.current_user:
        flash('发表新想法前请先登录!', category='error')
        return redirect(url_for('main.login'))
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post(form.title.data, form.content.data)
        new_post.publish_date = datetime.datetime.now()
        new_post.user = g.current_user
        new_post.category = PostCategory(form.category.data)

        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('.get_post', post_id=new_post.id))

    return render_template('add.html', form=form)

webapp/controllers/main.py
# coding: utf-8
''' main.py 主控制器蓝图
'''
import os
import time
import random
from io import BytesIO
from PIL import Image, ImageFilter, ImageFont, ImageDraw
from flask import render_template, Blueprint, redirect, url_for, flash, session, request, make_response, g
from webapp.models import db, User, Role, PostCategory
from webapp.forms import LoginForm, RegisterForm
from webapp.identicon import render_identicon

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.before_request
def check_user():
    if 'username' in session:
        g.current_user = User.query.filter_by(
            username=session["username"]
        ).one()
    else:
        g.current_user = None


def validate_picture():
    ''' 生成验证码
    '''
    total = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345789'
    # 图片大小130 x 50
    width = 130
    heighth = 50
    # 先生成一个新图片对象
    im = Image.new('RGB', (width, heighth), 'white')
    # 设置字体
    font = ImageFont.truetype('arial.ttf', 40)
    # font = ImageFont.load_default().font
    # font.size = 40
    # 创建draw对象
    draw = ImageDraw.Draw(im)
    str = ''
    # 输出每一个文字
    for item in range(5):
        text = random.choice(total)
        str += text
        draw.text((5+random.randint(4, 7)+20*item, 5 +
                   random.randint(3, 7)), text=text, fill='black', font=font)

    # 划几根干扰线
    for num in range(8):
        x1 = random.randint(0, width/2)
        y1 = random.randint(0, heighth/2)
        x2 = random.randint(0, width)
        y2 = random.randint(heighth/2, heighth)
        draw.line(((x1, y1), (x2, y2)), fill='black', width=1)

    # 模糊下,加个帅帅的滤镜～
    im = im.filter(ImageFilter.FIND_EDGES)
    return im, str


@main_blueprint.route('/')
def index():
    notice = "新站上线，请多关照！"
    # notice = ""
    return render_template('index.html', title="主页", notice=notice)


@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        session['username'] = form.username.data
        return redirect(url_for('.index'))

    return render_template('login.html', form=form)


@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = User(form.username.data)
        user.set_password(form.password.data)
        user.activated = True
        user.email = form.email.data
        user.roles.append(Role.query.filter_by(title='default').first())
        db.session.add(user)
        db.session.commit()

        session['username'] = form.username.data
        # 生成头像
        image_size = 40
        img = render_identicon(str(user.id ^ int(time.time()))[::-1], image_size)
        img.save(os.path.join(main_blueprint.root_path, "..", "static", 'uploads',
                              'avatars', '%s.jpg' % user.username))
        return redirect(url_for('.index'))
    return render_template('register.html', form=form)


@main_blueprint.route('/verify_code')
def get_verify_code():
    image, string = validate_picture()
    # 将验证码图片以二进制形式写入在内存中，防止将图片都放在文件夹中，占用大量磁盘
    buf = BytesIO()
    image.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    # 把二进制作为response发回前端，并设置首部字段
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/gif'
    # 将验证码字符串储存在session中
    session['image'] = string
    return response


@main_blueprint.route('/home/<string:username>')
def home(username):
    if not g.current_user or g.current_user.username != username:
        flash('请先登录再查看主页!', category='error')
        return redirect(url_for('main.login'))
    user = User.query.filter_by(
        username=username
    ).first()
    return render_template('home.html', user=user)


@main_blueprint.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('main.index'))

webapp/controllers/zako/views.py
import datetime
import json
from os import path
from flask import (
    render_template,
    Blueprint,
    redirect,
    url_for,
    session,
    g,
    flash,
    abort,
    request,
    make_response
)

from webapp.models import db, User, Script
from .zako_strategy import StrategyCompiler
from .zako_battle import battle

zako_blueprint = Blueprint(
    'zako',
    __name__,
    template_folder=path.join(path.pardir, '..', 'templates', 'zako'),
    url_prefix='/zako'
)


@zako_blueprint.before_request
def check_user():
    if 'username' in session:
        g.current_user = User.query.filter_by(
            username=session["username"]
        ).one()
    else:
        g.current_user = None


@zako_blueprint.route('/about')
def about():
    token_dict = {
        "Stategy": {
            "title": "策略开始标识",
            "usage": "Strategy T: expression",
            "description": "用法类似于常规编程语言中的 func 子程序。(必须)用在策略文件的开头，后面需要跟策略名 `T` 代表一个策略，`:` 后面是表达式。目前仅支持单文件单策略模式。",
        },
        "return": {
            "title": "策略结束标识",
            "usage": "return[ data]",
            "description": "用在策略结尾部分作为策略的输出结果。策略的输出结果会作为博弈的输入用于每一轮「博弈」过程中"
        },
        "COUNT": {
            "title": "当前博弈的回合数",
            "usage": "COUNT",
            "description": "保留字，用于获取当前「博弈」的回合数"
        },
        "FLAG": {
            "title": "「记忆伤痕」，表示是否被背叛过",
            "usage": "FLAG",
            "description": "保留字，判断直到目前为止的「博弈」中对方是否有过 “背叛” 选择"
        },
        "CUR": {
            "title": "「哨兵」，监视上一轮对方的选择",
            "usage": "COUNT",
            "description": "保留字，用于获取上一轮「博弈」时对方的选择"
        },
        "RANDOM": {
            "title": "随机函数",
            "usage": "RANDOM(n)",
            "description": "内置函数，随机返回 0 或 1"
        },
        "数据类型": {
            "title": "",
            "usage": "",
            "description": "由于在 Zako 语言中只存在 0 和 1，同时 0 也代表‘非判断’， 1 也代表 ‘是判断’"
        },
        "控制语句": {
            "title": "",
            "usage": "if (expression) {expression1} [else {expression2}]",
            "description": "常规语言的条件判断，负责实现分支流程，当 if(expression) 中的 expression 为是判断，则执行 expression1，否则，如果存在 else 分支，则执行 expression2 "
        }
    }

    token_list = ["数据类型", "控制语句", "Stategy",
                  "return", "COUNT", "FLAG", "CUR", "RANDOM"]
    return render_template(
        'about.html',
        token_list=token_list,
        token_dict=token_dict
    )


@zako_blueprint.route('/editor')
@zako_blueprint.route('/editor/<int:script_id>')
def editor(script_id=0):
    if script_id:
        script = Script.query.get(script_id)
        if script.user != g.current_user:
            abort(403)
        else:
            return render_template('editor.html', id=script.id, name=script.name, content=script.content, description=script.description)
    else:
        return render_template('editor.html')


@zako_blueprint.route('/verify', methods=['POST'])
def verify():
    content = request.values.get('content')
    if content is None or content == '':
        response = make_response('content 为空')
        response.status_code = 500
        return response
    strategy = StrategyCompiler(content)
    data = {'tree': strategy.parse_tree[0],
            'exception': strategy.parse_tree[1]}
    return json.dumps(data)


@zako_blueprint.route('/script/<script_id>', methods=['POST'])
@zako_blueprint.route('/script/', methods=['POST'])
def save_script(script_id=0):
    # 登录校验
    if not g.current_user:
        response = make_response('请先登录方可为自己保存策略脚本！')
        response.status_code = 403
        return response

    # 数据合法性校验
    name = request.values.get('name')
    if name is None or name == '':
        response = make_response('请填写文件名以便查找！')
        response.status_code = 501
        return response
    name = name+".sg" if not name.endswith('.sg') else name
    description = request.values.get('description', '')
    content = request.values.get('content')
    if content is None or content == '':
        response = make_response('请填写策略内容！')
        response.status_code = 501
        return response

    # 策略有效性校验
    try:
        strategy = StrategyCompiler(content)
        if strategy.parse_tree[1]:
            response = make_response('策略非法，请先校验！')
            response.status_code = 501
            return response

        if script_id != 0:
            script = Script.query.get(script_id)
        else:
            script = Script(name)
        script.content = content
        script.description = description
        script.user = g.current_user
        db.session.add(script)
        db.session.commit()

        response = {'message': '策略保存成功', 'id': script.id}

        return json.dumps(response)
    except Exception as e:
        response = {'message': '校验异常，请检查'}


@zako_blueprint.route('/scripts')
def get_scripts_library():
    public_library = Script.query.filter_by(
        is_private=False).order_by(Script.createtime)
    if g.current_user:
        private_library = Script.query.filter_by(
            user=g.current_user).order_by(Script.createtime.desc())
    else:
        private_library = []
    return render_template('library.html', public=public_library, private=private_library)


@zako_blueprint.route('/pve', methods=['GET'])
def pve():
    if not g.current_user:
        flash('请先登录再进行游戏!', category='error')
        return redirect(url_for('main.login'))
    public_library = Script.query.filter_by(
        is_private=False).order_by(Script.createtime)
    private_library = Script.query.filter_by(
        user=g.current_user).order_by(Script.createtime.desc())
    return render_template('pve.html', public=public_library, private=private_library)


@zako_blueprint.route('/fight', methods=['POST'])
def fight():
    if not g.current_user:
        return abort(403)
    attacker_id = request.values.get('attacker')
    defender_id = request.values.get('defender')
    round_number = int(request.values.get('round'))
    attacker_tree = Script.query.get(attacker_id).content
    defender_tree = Script.query.get(defender_id).content
    score_of_attacker, score_of_defender, pass_of_battle = battle(
        round_number, attacker_tree, defender_tree)
    # 处理战斗过程
    live = ""
    for index, item in enumerate(pass_of_battle):
        live += "第 {} 回合：<br/>".format(index+1)
        live += "玩家选择<b>{}</b>， 电脑选择<b>{}</b><br/>".format("合作" if item.attacker_choice ==
                                                           1 else "背叛", "合作" if item.defender_choice == 1 else "背叛")
        live += "当前比分 {} - {} <br/>".format(
            item.attacker_current_score, item.defender_current_score)
        live += "-----------------<br/>"
    # 处理最终结果
    if score_of_attacker > score_of_defender:
        flag = "victory"
    elif score_of_attacker == score_of_defender:
        flag = "draw"
    else:
        flag = "lose"
    data = {
        'flag': flag,
        'score': str(score_of_attacker) + ":" + str(score_of_defender),
        'live': live
    }
    return json.dumps(data)


@zako_blueprint.route('/pvp')
def pvp():
    return render_template('pvp.html')

webapp/templates/main/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %} - 比特大战</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/semantic.css') }}">
        <style>
        .main.container {
            margin-top: 7em;
        }
        </style>
    </head>
    <body>
        <div class="ui large fixed inverted menu">
            <div class="ui container">
                <a href="{{url_for('main.index')}}" class="header item">
                    <img class="logo", src="{{ url_for('static', filename='images/logo.png') }}" />
                    Bit War
                </a>
                <div class="ui simple dropdown item">
                    BattleField
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <a class="item" href="{{ url_for('zako.pvp') }}">和玩家 PK </a>
                        <a class="item" href="{{ url_for('zako.pve') }}">任务闯关</a>
                    </div>
                </div>
                <div class="ui simple dropdown item">
                    Zako 
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <a class="item" href="{{url_for('zako.about')}}">关于 Zako 语言</a>
                        <a class="item" href="{{url_for('zako.editor')}}">在线编辑器</a>
                        <a class="item" href="{{url_for('zako.get_scripts_library')}}">脚本库</a>
                    </div>
                </div>
                <div class="ui simple dropdown item">
                    Forum
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <a class="item" href="{{ url_for('forum.index', category='General', sort_key='recent', p=1) }}">综合</a>
                        <a class="item" href="{{ url_for('forum.index', category='QA', sort_key='recent', p=1) }}">问答求助</a>
                        <a class="item" href="{{ url_for('forum.index', category='Reality', sort_key='recent', p=1) }}">三次元</a>
                        <a class="item" href="{{ url_for('forum.index', category='TechTalk', sort_key='recent', p=1) }}">技术讨论</a>
                        <a class="item" href="{{ url_for('forum.index', category='Feedback', sort_key='recent', p=1) }}">意见反馈</a>
                    </div>
                </div>
                <div class="right menu">
                    {% if not g.current_user %}
                    <div class="item">
                        <div class="ui buttons">
                            <div class="ui blue button" onclick="window.location.href='{{ url_for('main.login') }}'">登录</div>
                            <div class="or"></div>
                            <div class="ui green button" onclick="window.location.href='{{ url_for('main.register') }}'">注册</div>
                        </div>
                    </div>
                    {% else %}
                    <div class="ui simple dropdown item">
                        <img class="ui avatar image" src="{{ url_for('static', filename='uploads/avatars/' + g.current_user.username + '.jpg') }}">
                        <span>{{ g.current_user.username }}</span>
                        <div class="menu">
                            <a class="item" href="{{ url_for('main.home', username=g.current_user.username) }}">进入主页</a>
                            <a class="item" href="{{ url_for('main.logout') }}">登出</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="ui main text container">
            {% block body %}
            {% endblock %}
        </div>
        <!--<div class="ui inverted vertical footer segment"></div>-->
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/semantic.js') }}"></script>
        {% block js %}
        {% endblock %}
    </body>
</html>

webapp/templates/main/home.html
{% extends "base.html" %}
{% block title %}{{ user.username }} 的个人主页{% endblock %}

{% block body %}
<div class="ui grid">
    <div class="two column row">
        <div class="column">
            <h2 class="ui header">
                <img src="{{ url_for('static', filename='uploads/avatars/' + user.username + '.jpg') }}" class="ui circular image"> 
                <div class="content">
                    {{ user.username }} 
                    <div class="sub header">昵称：{{ user.nickname }}</div>
                </div>
            </h2>
        </div>
    </div>
    <div class="row">
        <div class="column">
            <div class="ui top attached tabular menu">
                <a class="item active" data-tab="first">个人信息</a>
                <a class="item" data-tab="second">历史战绩</a>
                <a class="item" data-tab="third">我的发言</a>
            </div>
            <div class="ui bottom attached tab segment active" data-tab="first">
                欢迎你于 {{ user.createtime|datetimeformat("%Y-%m-%d %H:%M:%S") }} 首次登录「比特大战」。
            </div>
            <div class="ui bottom attached tab segment" data-tab="second">Second </div>
            <div class="ui bottom attached tab segment" data-tab="third">
                
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $('.menu .item').tab();
</script>
{% endblock %}

webapp/templates/main/index.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
    {% if notice %}    
    <div class="ui inverted segment">
        <p>最新公告: {{ notice }}</p>
    </div>
    {% endif %}
    <div class="ui piled segment">
        <div class="ui header">
            <div class="content">What is Bit War? </div>
            <div class="sub header">什么是『比特大战』？</div>
        </div>
        <p>
            『比特大战』的含义来源于《自私的基因》一书中，也是博弈论中常见的“囚徒困境”的一种。
        </p>
        <p>
            在『比特大战』中，在每一轮的博弈中存在着这样的博弈双方，他们之间可以选择“合作”或者“背叛”，根据自己的选择和对方的选择，经过一套规则计算可以得到它每一轮的得分。
            在若干个回合之后，博弈双方的总分对比，高者胜低者负。
        </p>
    </div>
    <div class="ui piled segment">
        <div class="ui header">
            <div class="content">Rule of Bit War? </div>
            <div class="sub header">『比特大战』的规则</div>
        </div>
        <p>
            『比特大战』的计算规则如下表格所示，其中竖列代表博弈方 <font color="red">A</font> 的选择，横行代表博弈方 <font color="blue">B</font> 的选择。
        </p>
        <p>
            <table class="ui definition table">
                <thead>
                    <tr>
                        <th></th>
                        <th>合作 work</th>
                        <th>背叛 betray</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>合作 work</td>
                        <td><font color="red">3</font>&nbsp;&nbsp;<font color="blue">3</font></td>
                        <td><font color="red">0</font>&nbsp;&nbsp;<font color="blue">5</font></td>
                    </tr>
                    <tr>
                        <td>背叛 betray</td>
                        <td><font color="red">5</font>&nbsp;&nbsp;<font color="blue">0</font></td>
                        <td><font color="red">1</font>&nbsp;&nbsp;<font color="blue">1</font></td>
                    </tr>
                </tbody>
            </table>
        </p>
    </div>
    <div class="ui piled segment">
        <div class="ui header">
            <div class="content">See a Bit War</div>
            <div class="sub header">观摩一场『比特大战』</div>
        </div>
        <div>
            <video src="http://vd3.bdstatic.com/mda-idbzmeb51dsjbv9h/mda-idbzmeb51dsjbv9h.mp4" controls="controls" width="100%"></video>
        </div>
    </div>
{% endblock %}

webapp/templates/main/login.html
{% extends "base.html" %}
{% block title %}用户登陆{% endblock %}
{% block body %}
<style>
    .show {
        display: block!important;
    }
</style>
<div class="ui middle aligned center grid">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="row">
        <div class="column">
            <div class="ui info message">
                <i class="close icon" id="close-tab"></i>
                <div class="header">系统阻止了你的操作并要求你登录</div>
                <ul class="list">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}
    {% endwith %}
    <div class="row">
        <div class="column">
            <h2 class="ui teal header center aligned">
                用户登陆
            </h2>
            <form class="ui large form" method="POST" action="{{ url_for('main.login') }}">
                {{ form.hidden_tag() }}
                <div class="ui stacked segment">
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="user icon"></i>
                            {{ form.username(placeholder=form.username.label.text)}}
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="lock icon"></i>
                            {{ form.password(placeholder=form.password.label.text)}}
                        </div>
                    </div>
                    <input type="submit" class="ui fluid large teal submit button" name="submit" value="登陆">
                </div>
                <div class="ui error message {% if form.errors_msgs %} show {% endif %}" >
                    {% if form.username.errors %}
                        <div class="header">无效的登陆行为</div>
                        {% for e in form.errors_msgs %}
                        <p>{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </form>
            <div class="ui message">
                没有账号? 赶紧来<a href="{{ url_for('.register') }}">注册</a>吧!
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    (function() {
        $('.message .close').on('click', function() {
            $(this).closest('.message').transition('fade');
        });
    })();
</script>
{% endblock %}

webapp/templates/main/register.html
{% extends "base.html" %}
{% block title %}新用户注册{% endblock %}
{% block body %}
<style>
    .show {
        display: block!important;
    }
</style>
<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal header">
            新用户注册
        </h2>
        <form class="ui large form" method="POST" action="{{ url_for('main.register') }}">
            {{ form.hidden_tag() }}
            <div class="ui stacked segment">
                <div class="field">
                    {% if form.username.errors %}
                    {% for e in form.username.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        {{ form.username(placeholder=form.username.label.text)}}
                    </div>
                </div>
                <div class="field">
                    {% if form.email.errors %}
                    {% for e in form.email.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    <div class="ui left icon input">
                        <i class="mail icon"></i>
                        {{ form.email(placeholder=form.email.label.text)}}
                    </div>
                </div>
                <div class="field">
                    {% if form.password.errors %}
                    {% for e in form.password.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{ form.password(placeholder=form.password.label.text)}}
                    </div>
                </div>
                <div class="field">
                    {% if form.confirm.errors %}
                    {% for e in form.confirm.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{ form.confirm(placeholder=form.confirm.label.text)}}
                    </div>
                </div>
                <div class="field">
                    {% if form.verification_code.errors %}
                    {% for e in form.verification_code.errors %}
                        <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    <div class="ui left icon input">
                        <img class="ui small image" src="{{ url_for('.get_verify_code') }}" onclick="this.src='{{ url_for('.get_verify_code') }}?'+Math.random();">
                        {{ form.verification_code(placeholder="请填写 5 位验证码")}}
                    </div>
                </div>
                <input type="submit" class="ui fluid large teal submit button" name="submit" value="注册">
            </div>
            <div class="ui error message {% if form.errors_msgs %} show {% endif %}" >
                {% if form.errors_msgs %}
                    <div class="header">出错信息</div>
                    {% for e in form.errors_msgs %}
                    <p>{{ e }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </form>
    </div>
</div>
{% endblock %}