webapp/__init__.py
from flask import Flask, redirect, url_for

from .models import db, User, Role
from .controllers.main import main_blueprint
from .controllers.zako.views import zako_blueprint
from .controllers.forum import forum_blueprint
from .extensions import bcrypt
from .filters import datetimeformat


def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    bcrypt.init_app(app)

    app.register_blueprint(main_blueprint)
    app.register_blueprint(zako_blueprint)
    app.register_blueprint(forum_blueprint)

    app.jinja_env.filters['datetimeformat'] = datetimeformat

    return app


if __name__ == "__main__":
    app = create_app()

webapp/controllers/forum.py
# coding: utf-8
''' forum 论坛控制器视图
'''
import datetime
from collections import namedtuple
from sqlalchemy import func
from flask import render_template, Blueprint, redirect, url_for, flash, session, request, make_response, g, abort
from webapp.models import db, User, Post, Comment, PostCategory
from webapp.forms import PostForm, CommentForm, select_choice_names


forum_blueprint = Blueprint(
    'forum',
    __name__,
    template_folder='../templates/forum',
    url_prefix='/forum'
)

category_tuple = namedtuple('Category', ['code', 'name'])
sort_key_tuple = namedtuple('SortKey', ['code', 'name'])


categories = {k: v for (k, v) in [(x.code, x) for x in (category_tuple(
    x[0], x[1]) for x in zip([i.name for i in PostCategory], select_choice_names))]}
sort_keys = {
    'recent': sort_key_tuple('recent', '最新'),
    'hotest': sort_key_tuple('hotest', '最热')
}


@forum_blueprint.before_request
def check_user():
    if 'username' in session:
        g.current_user = User.query.filter_by(
            username=session["username"]
        ).one()
    else:
        g.current_user = None


@forum_blueprint.route('/<string:category>/<string:sort_key>')
def index(category, sort_key):
    page = request.args.get('p', 1, type=int)
    print(page)
    if category not in categories.keys():
        abort(404)
    if sort_key not in sort_keys.keys():
        abort(404)
    if sort_key == "recent":
        posts = db.session.query(Post, func.count(Comment.post_id).label(
            'total_comments')).join(Comment, isouter=True).filter(Post.category == category).group_by(Post.id).order_by(Post.publish_date.desc()).paginate(int(page), 10, False)
    else:
        posts = db.session.query(Post, func.count(Comment.post_id).label('total_comments')).join(Comment, isouter=True).filter(
            Post.category == category).group_by(Post.id).order_by('total_comments DESC').paginate(int(page), 10, False)
    return render_template('forum.html', category=categories[category], sort=sort_keys[sort_key], posts=posts)


@forum_blueprint.route('/t/<int:post_id>', methods=['GET', 'POST'])
def get_post(post_id):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    if g.current_user and form.validate_on_submit():
        comment = Comment(form.text.data)
        comment.post_id = post_id
        comment.user_id = g.current_user.id
        comment.date = datetime.datetime.now()
        db.session.add(comment)
        db.session.commit()
        form.text.data = ""

    return render_template('post.html', post=post, form=form)


@forum_blueprint.route('/add', methods=['GET', 'POST'])
def add_post():
    if not g.current_user:
        flash('发表新想法前请先登录!', category='error')
        return redirect(url_for('main.login'))
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post(form.title.data, form.content.data)
        new_post.publish_date = datetime.datetime.now()
        new_post.user = g.current_user
        new_post.category = PostCategory(form.category.data)

        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('.get_post', post_id=new_post.id))

    return render_template('add.html', form=form)

webapp/controllers/main.py
# coding: utf-8
''' main.py 主控制器蓝图
'''
import os
import time
import random
from io import BytesIO
from PIL import Image, ImageFilter, ImageFont, ImageDraw
from flask import render_template, Blueprint, redirect, url_for, flash, session, request, make_response, g
from webapp.models import db, User, Role, PostCategory
from webapp.forms import LoginForm, RegisterForm
from webapp.identicon import render_identicon

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.before_request
def check_user():
    if 'username' in session:
        g.current_user = User.query.filter_by(
            username=session["username"]
        ).one()
    else:
        g.current_user = None


def validate_picture():
    ''' 生成验证码
    '''
    total = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345789'
    # 图片大小130 x 50
    width = 130
    heighth = 50
    # 先生成一个新图片对象
    im = Image.new('RGB', (width, heighth), 'white')
    # 设置字体
    font = ImageFont.truetype('arial.ttf', 40)
    # font = ImageFont.load_default().font
    # font.size = 40
    # 创建draw对象
    draw = ImageDraw.Draw(im)
    str = ''
    # 输出每一个文字
    for item in range(5):
        text = random.choice(total)
        str += text
        draw.text((5+random.randint(4, 7)+20*item, 5 +
                   random.randint(3, 7)), text=text, fill='black', font=font)

    # 划几根干扰线
    for num in range(8):
        x1 = random.randint(0, width/2)
        y1 = random.randint(0, heighth/2)
        x2 = random.randint(0, width)
        y2 = random.randint(heighth/2, heighth)
        draw.line(((x1, y1), (x2, y2)), fill='black', width=1)

    # 模糊下,加个帅帅的滤镜～
    im = im.filter(ImageFilter.FIND_EDGES)
    return im, str


@main_blueprint.route('/')
def index():
    notice = "新站上线，请多关照！"
    # notice = ""
    return render_template('index.html', title="主页", notice=notice)


@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        session['username'] = form.username.data
        return redirect(url_for('.index'))

    return render_template('login.html', form=form)


@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        user = User(form.username.data)
        user.set_password(form.password.data)
        user.activated = True
        user.email = form.email.data
        user.roles.append(Role.query.filter_by(title='default').first())
        db.session.add(user)
        db.session.commit()

        session['username'] = form.username.data
        # 生成头像
        image_size = 40
        img = render_identicon(str(user.id ^ int(time.time()))[::-1], image_size)
        img.save(os.path.join(main_blueprint.root_path, "..", "static", 'uploads',
                              'avatars', '%s.jpg' % user.username))
        return redirect(url_for('.index'))
    return render_template('register.html', form=form)


@main_blueprint.route('/verify_code')
def get_verify_code():
    image, string = validate_picture()
    # 将验证码图片以二进制形式写入在内存中，防止将图片都放在文件夹中，占用大量磁盘
    buf = BytesIO()
    image.save(buf, 'jpeg')
    buf_str = buf.getvalue()
    # 把二进制作为response发回前端，并设置首部字段
    response = make_response(buf_str)
    response.headers['Content-Type'] = 'image/gif'
    # 将验证码字符串储存在session中
    session['image'] = string
    return response


@main_blueprint.route('/home/<string:username>')
def home(username):
    if not g.current_user or g.current_user.username != username:
        flash('请先登录再查看主页!', category='error')
        return redirect(url_for('main.login'))
    user = User.query.filter_by(
        username=username
    ).first()
    return render_template('home.html', user=user)


@main_blueprint.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('main.index'))

webapp/controllers/zako/views.py
import datetime
import json
from os import path
from flask import (
    render_template,
    Blueprint,
    redirect,
    url_for,
    session,
    g,
    flash,
    abort,
    request,
    make_response
)

from webapp.models import db, User, Script
from .zako_strategy import StrategyCompiler
from .zako_battle import battle

zako_blueprint = Blueprint(
    'zako',
    __name__,
    template_folder=path.join(path.pardir, '..', 'templates', 'zako'),
    url_prefix='/zako'
)


@zako_blueprint.before_request
def check_user():
    if 'username' in session:
        g.current_user = User.query.filter_by(
            username=session["username"]
        ).one()
    else:
        g.current_user = None


@zako_blueprint.route('/about')
def about():
    token_dict = {
        "Stategy": {
            "title": "策略开始标识",
            "usage": "Strategy T: expression",
            "description": "用法类似于常规编程语言中的 func 子程序。(必须)用在策略文件的开头，后面需要跟策略名 `T` 代表一个策略，`:` 后面是表达式。目前仅支持单文件单策略模式。",
        },
        "return": {
            "title": "策略结束标识",
            "usage": "return[ data]",
            "description": "用在策略结尾部分作为策略的输出结果。策略的输出结果会作为博弈的输入用于每一轮「博弈」过程中"
        },
        "COUNT": {
            "title": "当前博弈的回合数",
            "usage": "COUNT",
            "description": "保留字，用于获取当前「博弈」的回合数"
        },
        "FLAG": {
            "title": "「记忆伤痕」，表示是否被背叛过",
            "usage": "FLAG",
            "description": "保留字，判断直到目前为止的「博弈」中对方是否有过 “背叛” 选择"
        },
        "CUR": {
            "title": "「哨兵」，监视上一轮对方的选择",
            "usage": "COUNT",
            "description": "保留字，用于获取上一轮「博弈」时对方的选择"
        },
        "RANDOM": {
            "title": "随机函数",
            "usage": "RANDOM(n)",
            "description": "内置函数，随机返回 0 或 1"
        },
        "数据类型": {
            "title": "",
            "usage": "",
            "description": "由于在 Zako 语言中只存在 0 和 1，同时 0 也代表‘非判断’， 1 也代表 ‘是判断’"
        },
        "控制语句": {
            "title": "",
            "usage": "if (expression) {expression1} [else {expression2}]",
            "description": "常规语言的条件判断，负责实现分支流程，当 if(expression) 中的 expression 为是判断，则执行 expression1，否则，如果存在 else 分支，则执行 expression2 "
        }
    }

    token_list = ["数据类型", "控制语句", "Stategy",
                  "return", "COUNT", "FLAG", "CUR", "RANDOM"]
    return render_template(
        'about.html',
        token_list=token_list,
        token_dict=token_dict
    )


@zako_blueprint.route('/editor')
@zako_blueprint.route('/editor/<int:script_id>')
def editor(script_id=0):
    if script_id:
        script = Script.query.get(script_id)
        if script.user != g.current_user:
            abort(403)
        else:
            return render_template('editor.html', id=script.id, name=script.name, content=script.content, description=script.description)
    else:
        return render_template('editor.html')


@zako_blueprint.route('/verify', methods=['POST'])
def verify():
    content = request.values.get('content')
    if content is None or content == '':
        response = make_response('content 为空')
        response.status_code = 500
        return response
    strategy = StrategyCompiler(content)
    data = {'tree': strategy.parse_tree[0],
            'exception': strategy.parse_tree[1]}
    return json.dumps(data)


@zako_blueprint.route('/script/<script_id>', methods=['POST'])
@zako_blueprint.route('/script/', methods=['POST'])
def save_script(script_id=0):
    # 登录校验
    if not g.current_user:
        response = make_response('请先登录方可为自己保存策略脚本！')
        response.status_code = 403
        return response

    # 数据合法性校验
    name = request.values.get('name')
    if name is None or name == '':
        response = make_response('请填写文件名以便查找！')
        response.status_code = 501
        return response
    name = name+".sg" if not name.endswith('.sg') else name
    description = request.values.get('description', '')
    content = request.values.get('content')
    if content is None or content == '':
        response = make_response('请填写策略内容！')
        response.status_code = 501
        return response

    # 策略有效性校验
    try:
        strategy = StrategyCompiler(content)
        if strategy.parse_tree[1]:
            response = make_response('策略非法，请先校验！')
            response.status_code = 501
            return response

        if script_id != 0:
            script = Script.query.get(script_id)
        else:
            script = Script(name)
        script.content = content
        script.description = description
        script.user = g.current_user
        db.session.add(script)
        db.session.commit()

        response = {'message': '策略保存成功', 'id': script.id}

        return json.dumps(response)
    except Exception as e:
        response = {'message': '校验异常，请检查'}


@zako_blueprint.route('/scripts')
def get_scripts_library():
    public_library = Script.query.filter_by(
        is_private=False).order_by(Script.createtime)
    if g.current_user:
        private_library = Script.query.filter_by(
            user=g.current_user).order_by(Script.createtime.desc())
    else:
        private_library = []
    return render_template('library.html', public=public_library, private=private_library)


@zako_blueprint.route('/pve', methods=['GET'])
def pve():
    if not g.current_user:
        flash('请先登录再进行游戏!', category='error')
        return redirect(url_for('main.login'))
    public_library = Script.query.filter_by(
        is_private=False).order_by(Script.createtime)
    private_library = Script.query.filter_by(
        user=g.current_user).order_by(Script.createtime.desc())
    return render_template('pve.html', public=public_library, private=private_library)


@zako_blueprint.route('/fight', methods=['POST'])
def fight():
    if not g.current_user:
        return abort(403)
    attacker_id = request.values.get('attacker')
    defender_id = request.values.get('defender')
    round_number = int(request.values.get('round'))
    attacker_tree = Script.query.get(attacker_id).content
    defender_tree = Script.query.get(defender_id).content
    score_of_attacker, score_of_defender, pass_of_battle = battle(
        round_number, attacker_tree, defender_tree)
    # 处理战斗过程
    live = ""
    for index, item in enumerate(pass_of_battle):
        live += "第 {} 回合：<br/>".format(index+1)
        live += "玩家选择<b>{}</b>， 电脑选择<b>{}</b><br/>".format("合作" if item.attacker_choice ==
                                                           1 else "背叛", "合作" if item.defender_choice == 1 else "背叛")
        live += "当前比分 {} - {} <br/>".format(
            item.attacker_current_score, item.defender_current_score)
        live += "-----------------<br/>"
    # 处理最终结果
    if score_of_attacker > score_of_defender:
        flag = "victory"
    elif score_of_attacker == score_of_defender:
        flag = "draw"
    else:
        flag = "lose"
    data = {
        'flag': flag,
        'score': str(score_of_attacker) + ":" + str(score_of_defender),
        'live': live
    }
    return json.dumps(data)


@zako_blueprint.route('/pvp')
def pvp():
    return render_template('pvp.html')

webapp/templates/zako/about.html
{% extends "base.html" %}
{% block title %}关于 Zako 语言{% endblock %}

{% block body %}
    <div class="ui grid" id="about">
        <h1 class="ui header">关于 Zako 语言</h1>
        <div class="row">
            <div class="column">
                <p>
                    Zako 语言的设计初衷，来自于当初编译原理课程项目中对于实现「自私的基因」中类似于“囚徒困境”模拟，要求提供一种语言工具可以恰当的描述至少 5 种博弈的模拟，Zako 语言就是在这种情况下被创造出来了。
                    <br/>
                    严格来说，Zako 可能连 DSL 都算不上，充其量就是一个 Toy Script。但我的想法是语言始终是为场景服务的，既然我的目标是模拟，所以它得足够简单以至于能快速上手，才能不干扰我们模拟的进程。
                    <br/>
                    希望下面的在线语法手册可以帮助你理解这个语言 :) 。
                </p>
            </div>
        </div>
    </div>
    <div class="ui grid" style="margin-top: 50px;" id="manual">
        <h1 class="ui header">在线手册</h1>
        <div class="row">
            <div class="four wide column">
                <div class="ui vertical fluid left menu">
                    <a class="item active" id="define">定义</a>
                    <a class="item" id="example">策略示例</a>
                    <div class="ui item dropdown" id="token">
                        <i class="dropdown icon"></i>
                        语法
                        <div class="menu">
                            {% for token in token_list %}
                            <div class="item">{{ token }}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="twelve wide stretched column content">
                <div class="ui segment content" id="define-content">
                    <h3 class="ui header">博弈</h3>
                    <p>
                        博弈是以<b>回合</b>计算。『比特大战』开始的时候需要设置博弈的回合数，每一轮的博弈需要博弈双方的输入，得到博弈回合各自的比分，即
                        <br/>
                        <pre style="color: #D6D6D6; background-color: rgb(93,93,93);text-align:center;">output(A, B) = f(input(A), input(B))</pre>
                        其中：
                        <ul>
                            <li><span class="ui tiny pink header">output(A, B)</span> 为 A、B 双方得分，取值集合为 ((1,1), (0,5), (5,0), (3,3)) </li>
                            <li><span class="ui tiny pink header">f(S(A), S(B))</span> 为博弈计算规则（即囚徒规则）</li>
                            <li><span class="ui tiny pink header">input(X)</span> 为策略计算</li>
                        </ul>
                    </p>
                    <div class="ui section divider"></div>
                    <h3 class="ui header">策略</h3>
                    <p>
                        策略即是在每一次博弈中博弈双方 A、B 所做出选择的过程，利用上式可知：
                        <pre style="color: #D6D6D6; background-color: rgb(93,93,93);text-align:center;">(1, 0) = input(X)</pre>
                        可见<b>策略</b>也是 SGN 函数的一种。
                    </p>
                </div>
                <div class="ui segment content" style="display: none; margin-top:0;" id="token-content">
                    <h2 class="ui header"></h2>
                    <div class="ui divider"></div>
                    <h3 class="ui header">名称</h3>
                    <p></p>
                    <h3 class="ui header">用法</h3>
                    <p></p>
                    <h3 class="ui header">说明</h3>
                    <p>说明</p>
                </div>
                <div class="ui segment content" id="example-content" style="display: none; margin-top:0;">
                    <h3 class="ui small header">示例一：永远合作</h3>
                    <pre>
    Strategy AlwayWork:
        return 1
                    </pre>
                    <div class="ui divider"></div>
                    <h3 class="ui small header">示例二：随机背叛</h3>
                    <pre>
    Strategy RandomBetray:
        i = RANDOM(3);
        if(i==3)
        {return 0}
        else
        {return 1}
                    </pre>
                    <div class="ui divider"></div>
                    <p>更多的示例可以浏览公共库：<a href="{{ url_for('zako.get_scripts_library')}}">点我前往</a></p>
                </div> 
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script>
    var token_dict= {{ token_dict|tojson }}
</script>
<script src="{{ url_for('static', filename='js/menu.js') }}"></script>
{% endblock %}

webapp/templates/zako/editor.html
{% extends "base.html" %}
{% block title %}Zako 在线编辑器{% endblock %}

{% block body %}
<div class="ui grid">
    <h1 class="ui header">策略编辑器 - 基于 Zako</h1>
    <div class="ten wide column">
        <form class="ui form">
            <div class="field">
                <label>文件名<span style="color: red">*</span></label>
                <input type="text" name="name" placeholder="例如：xxx.sg，默认后缀 .sg" {% if name %}value="{{ name }}" {% endif %}/>
            </div>
            <div class="field">
                <label>描述</label>
                <input type="text" name="description" placeholder="例如：永远合作" {% if description %}value="{{ description }}" {% endif %}/>
            </div>
            <div class="field">
                <label>内容<span style="color: red">*</span></label>
                <textarea name="content" >{% if content %}{{ content.strip() }}{% else %}Strategy Demo:
    return 1{% endif %}</textarea>
            </div>
        </form>
        <div class="ui buttons" style="margin-top: 20px">
            {% if g.current_user %}
            <button class="ui primary button" id="save">保存</button>
            {% endif %}
            <button class="ui secondary button" id="verify">校验</button>
            <button class="ui button" id="upload">上传</button>
        </div>
    </div>
    <div class="six wide column">
        <div class="ui card" id="message-card">
            <div class="content">
                <div class="header">校验结果</div>
                <div class="ui inverted divider"></div>
                <div class="meta"><span class="ui tiny header"></span></div>
                <div class="description">
                    无校验结果
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="ten column" id="save-message">
            <div class="ui warning message hidden"><i class="warning icon"></i><span></span></div>
            <div class="ui positive message hidden"><i class="checkmark icon"></i><span></span></div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    $(function(){
        // 显示校验信息
        var showVerifyMessage = function(content, result_code) {
            if (result_code == 0) {
                $('#message-card .meta span').addClass('red').removeClass('green').removeClass('yellow').text('校验异常');
                $('#message-card .description').text(content);
            }
            else if (result_code == -1) {
                $('#message-card .meta span').addClass('yellow').removeClass('green').removeClass('red').text('失败');
                $('#message-card .description').text("异常信息: " + content);
            }
            else if (result_code == 1) {
                $('#message-card .meta span').addClass('green').removeClass('red').removeClass('yellow').text('成功');
                $('#message-card .description').text("生成语法树: \r\n" + content);
            }
        };

        // 显示保存信息
        var showSaveMessage = function(content, isSuccess) {
            if(isSuccess) {
                $('#save-message div.warning.message').addClass('hidden');
                $('#save-message div.positive.message').removeClass('hidden').find('span').text(content);
                setTimeout(function() { $('#save-message div.positive.message').addClass('hidden'); }, 2500);
            }
            else {
                $('#save-message div.positive.message').addClass('hidden');
                $('#save-message div.warning.message').removeClass('hidden').find('span').text(content).show(20).addClass('hidden');
                setTimeout(function() { $('#save-message div.warning.message').addClass('hidden'); }, 2500);
            }
        }

        // 校验
        $("#verify").click(function(){
            var content=$('[name=content]').val();
            var data= {
                content: content
            }
            $.ajax({
                url:'{{ url_for("zako.verify") }}',
                type:'POST',
                data:data,
                dataType: 'json',
                success:function(res){
                    console.log(res);
                    if(res.exception)
                        showVerifyMessage(res.exception, -1);
                    else
                        showVerifyMessage(res.tree, 1);
                },
                error:function (res) {
                    console.log(res);
                    showVerifyMessage(res.responseText, 0);
                }
            })
        });
        
        // 保存
        $("#save").click(function(){
            var name=$('[name=name]').val();
            var description=$('[name=description]').val();
            var content=$('[name=content]').val();
            var url = '{{ url_for("zako.save_script", script_id = id if id) }}';
            if(name.length == 0 || content.length == 0) {
                alert('请填写策略文件名以及内容！');
                return;
            }
                
            var data= {
                name: name,
                description: description,
                content: content
            }
                $.ajax({
                url:url,
                type:'POST',
                data:data,
                dataType: 'json',
                success:function(res){
                    console.log(res);
                    showSaveMessage(res.message, true);
                },
                error:function (res) {
                    showSaveMessage(res.responseText, false);
                }
            })
        });
    })
</script>
{% endblock %}

webapp/templates/zako/library.html
{% extends "base.html" %}
{% block title %}脚本库{% endblock %}
{% block body %}

<div class="ui grid">
    <h1 class="ui header">Bit War 脚本库</h1>
    <div class="sixteen wide column">
        <div class="ui styled accordion">
            <div class="active title"><i class="dropdown icon"></i> 公共库 </div>
            <div class="active content">
                <div class="ui three column grid transition">
                    {% for item in public %} 
                    <div class="column">
                        <div class="ui fluid card">
                            <div class="image" data-tooltip="{{ item.description }}" data-position="bottom center">
                                <img src="{{ url_for('static', filename="images/script.jpg") }}">
                            </div>
                            <!-- <div class="ui small circular rotate reveal image">
                                <div class="visible content">
                                    <img src="{{ url_for('static', filename="images/script.jpg") }}">
                                </div>
                                <div class="hidden content">
                                    <p>{{ item.description }}</p>
                                </div>
                            </div> -->
                            <div class="content">
                                <a style="word-wrap: break-word;word-break: break-word;">{{ item.name[:-3] }}</a>
                                <div class="meta">
                                    <span>创建于 <br/>{{ item.createtime | datetimeformat("%Y-%m-%d") }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% if g.current_user %}
            <div class="title"><i class="dropdown icon"></i> 私有库 </div>
            <div class="content">
                <div class="ui three column grid transition">
                    {% for item in private %} 
                    <div class="column">
                        <div class="ui fluid card">
                            <div class="image" data-tooltip="{{ item.description }}" data-position="bottom center">
                                <img src="{{ url_for('static', filename="images/script.jpg") }}">
                            </div>
                            <div class="content">
                                <a class="ui tiny header" href="{{ url_for('zako.editor', script_id=item.id)}}">{{ item.name[:-3] }}</a>
                                <div class="meta">
                                    <a>创建于 <br/>{{ item.createtime | datetimeformat("%Y-%m-%d") }}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script>
    (function() {
        /* 初始化折叠控件 */
        $('.ui.accordion')
        .accordion();

        $('.trigger.example .accordion')
        .accordion({
            selector: {
                trigger: '.title .icon'
            }
        })
        ;
    })();
</script>
{% endblock %}

webapp/templates/zako/pvp.html
{% extends "base.html" %}
{% block title %}玩家对战{% endblock %}
{% block body %}
<div class="ui grid">
    <h2 class="ui header">功能开发中，敬请期待</h2>
</div>
{% endblock %}